service: smart-hat-engine

custom:
  awsAccountId:
    Ref: AWS::AccountId

provider:
  name: aws
  runtime: java8
  region: eu-west-1
  stage: dev
  memorySize: 256
  versionFunctions: false
  timeout: 10
  logRetentionInDays: 1
  endpointType: regional

package:
  individually: true
  artifact: artifacts/data-feed-counter.jar

functions:

  dataFeedCounter:
    handler: org.hatdex.hat.she.functions.DataFeedCounterHandler::handle
    package:
      individually: true
      artifact: artifacts/data-feed-counter.jar
    events:
      - http:
          path: data-feed-counter/1.0.0
          method: post

  dataFeedCounterConfiguration:
    handler: org.hatdex.hat.she.functions.DataFeedCounterConfigurationHandler::handle
    package:
      individually: true
      artifact: artifacts/data-feed-counter.jar
    events:
      - http:
          path: data-feed-counter/1.0.0/configuration
          method: get

  dataFeedCounterBundle:
    handler: org.hatdex.hat.she.functions.DataFeedCounterBundleHandler::handle
    package:
      individually: true
      artifact: artifacts/data-feed-counter.jar
    events:
      - http:
          path: data-feed-counter/1.0.0/data-bundle
          method: get

  sentimentTracker:
    handler: org.hatdex.hat.she.functions.SentimentTrackerHandler::handle
    package:
      individually: true
      artifact: artifacts/sentiment-tracker.jar
    memorySize: 1024
    timeout: 120
    events:
      - http:
          path: sentiment-tracker/1.0.0
          method: post

  sentimentTrackerConfiguration:
    handler: org.hatdex.hat.she.functions.SentimentTrackerConfigurationHandler::handle
    package:
      individually: true
      artifact: artifacts/sentiment-tracker.jar
    memorySize: 1024
    events:
      - http:
          path: sentiment-tracker/1.0.0/configuration
          method: get

  sentimentTrackerBundle:
    handler: org.hatdex.hat.she.functions.SentimentTrackerBundleHandler::handle
    package:
      individually: true
      artifact: artifacts/sentiment-tracker.jar
    memorySize: 1024
    events:
      - http:
          path: sentiment-tracker/1.0.0/data-bundle
          method: get

