service: dswift-she

plugins:
  - serverless-plugin-select

configValidationMode: off

custom:
  awsAccountId:
    Ref: AWS::AccountId
  region: eu-west-1
  profile:
    staging: dataswift-staging
    sandbox: dataswift-sandbox
    production: dataswift-production
    legacy: dataswift-master
    direct: dataswift-master
  stackName:
    staging: dswift-hat-stage
    sandbox: dswift-hat-sandbox
    production: dswift-hat-production
    legacy: hubofallthings-net
    direct: hatdirect

provider:
  name: aws
  runtime: java8
  region: ${opt:region,'eu-west-1'}
  profile: ${self:custom.profile.${self:provider.stage}}
  stage: ${opt:stage,'staging'}
  memorySize: 256
  versionFunctions: false
  timeout: 10
  logRetentionInDays: 30
  endpointType: regional
  vpc:
    securityGroupIds:
      - Fn::ImportValue: ${self:custom.stackName.${self:provider.stage}}-she-security-group
    subnetIds:
      - Fn::ImportValue: ${self:custom.stackName.${self:provider.stage}}-restricted-subnet-id-az1
      - Fn::ImportValue: ${self:custom.stackName.${self:provider.stage}}-restricted-subnet-id-az2

package:
  individually: true
  artifact: artifacts/data-feed-counter.jar

functions:

  api-data-feed-counter:
    handler: org.hatdex.hat.she.functions.DataFeedCounterProxyHandler::handle
    stages:
      - staging
      - sandbox
      - legacy
      - direct
    package:
      individually: true
      artifact: artifacts/data-feed-counter.jar
    timeout: 120
    events:
      - http:
          path: data-feed-counter/1.0.0
          method: post

  api-data-feed-counter-configuration:
    handler: org.hatdex.hat.she.functions.DataFeedCounterConfigurationProxyHandler::handle
    stages:
      - staging
      - sandbox
      - legacy
      - direct
    package:
      individually: true
      artifact: artifacts/data-feed-counter.jar
    events:
      - http:
          path: data-feed-counter/1.0.0/configuration
          method: get

  api-data-feed-counter-bundle:
    handler: org.hatdex.hat.she.functions.DataFeedCounterBundleProxyHandler::handle
    stages:
      - staging
      - sandbox
      - legacy
      - direct
    package:
      individually: true
      artifact: artifacts/data-feed-counter.jar
    events:
      - http:
          path: data-feed-counter/1.0.0/data-bundle
          method: get

  data-feed-counter:
    handler: org.hatdex.hat.she.functions.DataFeedCounterHandler::handle
    stages:
      - staging
      - sandbox
      - legacy
      - direct
    package:
      individually: true
      artifact: artifacts/data-feed-counter.jar
    timeout: 120

  data-feed-counter-configuration:
    handler: org.hatdex.hat.she.functions.DataFeedCounterConfigurationHandler::handle
    stages:
      - staging
      - sandbox
      - legacy
      - direct
    package:
      individually: true
      artifact: artifacts/data-feed-counter.jar

  data-feed-counter-bundle:
    handler: org.hatdex.hat.she.functions.DataFeedCounterBundleHandler::handle
    stages:
      - staging
      - sandbox
      - legacy
      - direct
    package:
      individually: true
      artifact: artifacts/data-feed-counter.jar

  api-sentiment-tracker:
    handler: org.hatdex.hat.she.functions.SentimentTrackerProxyHandler::handle
    stages:
      - staging
      - sandbox
      - legacy
      - direct
    package:
      individually: true
      artifact: artifacts/sentiment-tracker.jar
    memorySize: 1024
    timeout: 120
    events:
      - http:
          path: sentiment-tracker/1.0.0
          method: post

  api-sentiment-tracker-configuration:
    handler: org.hatdex.hat.she.functions.SentimentTrackerConfigurationProxyHandler::handle
    stages:
      - staging
      - sandbox
      - legacy
      - direct
    package:
      individually: true
      artifact: artifacts/sentiment-tracker.jar
    memorySize: 1024
    events:
      - http:
          path: sentiment-tracker/1.0.0/configuration
          method: get

  api-sentiment-tracker-bundle:
    handler: org.hatdex.hat.she.functions.SentimentTrackerBundleProxyHandler::handle
    stages:
      - staging
      - sandbox
      - legacy
      - direct
    package:
      individually: true
      artifact: artifacts/sentiment-tracker.jar
    memorySize: 1024
    events:
      - http:
          path: sentiment-tracker/1.0.0/data-bundle
          method: get

  sentiment-tracker:
    handler: org.hatdex.hat.she.functions.SentimentTrackerHandler::handle
    stages:
      - staging
      - sandbox
      - legacy
      - direct
    package:
      individually: true
      artifact: artifacts/sentiment-tracker.jar
    memorySize: 1024
    timeout: 300

  sentiment-tracker-configuration:
    handler: org.hatdex.hat.she.functions.SentimentTrackerConfigurationHandler::handle
    stages:
      - staging
      - sandbox
      - legacy
      - direct
    package:
      individually: true
      artifact: artifacts/sentiment-tracker.jar
    memorySize: 1024

  sentiment-tracker-bundle:
    handler: org.hatdex.hat.she.functions.SentimentTrackerBundleHandler::handle
    stages:
      - staging
      - sandbox
      - legacy
      - direct
    package:
      individually: true
      artifact: artifacts/sentiment-tracker.jar
    memorySize: 1024
